# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: C# unit test CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
    - name: Test with dotnet
          run: |
              dotnet test
